server:
  port: 8090
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: bc5ad731ac8dca4ac718
            client-secret: 69e70b37a0fcbcb01734f6cd9dd2af155d0837ef
          google:
            client-id: 1025165672851-kd5qs6e919mb9uieedflokje4d7jrosn.apps.googleusercontent.com
            client-secret: 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
  datasource:
    url: jdbc:postgresql://localhost:5432/stocksAuth
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true;
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE